Fix observe issue on worker thread
cafebazaar/CafeBazaarAuth pull request #16
Opened 2020-12-14 09:26 UTC by shayanpourvatan

2020-12-14 10:06 UTC, PHELAT requested changes

2020-12-14 10:06 UTC, PHELAT commented on auth/src/main/java/com/farsitel/bazaar/thread/MainThread.kt
> +class MainThread : Handler(Looper.getMainLooper())
Make this an `internal class`.

2020-12-14 10:06 UTC, PHELAT commented on auth/src/main/java/com/farsitel/bazaar/thread/ThreadHelper.kt
> +object ThreadHelper {
Make this an `internal object`.

2020-12-14 10:06 UTC, PHELAT commented on sample/src/main/java/com/farsitel/bazaar/sample/auth/MainActivity.kt
> +                println("Use already login ${response.data?.accountId}")
"User already logged in".

2020-12-14 10:36 UTC, shayanpourvatan commented on auth/src/main/java/com/farsitel/bazaar/thread/ThreadHelper.kt
> +object ThreadHelper {
Done

2020-12-14 10:36 UTC, shayanpourvatan commented on sample/src/main/java/com/farsitel/bazaar/sample/auth/MainActivity.kt
> +                println("Use already login ${response.data?.accountId}")
Done

2020-12-14 10:36 UTC, shayanpourvatan commented on auth/src/main/java/com/farsitel/bazaar/thread/MainThread.kt
> +class MainThread : Handler(Looper.getMainLooper())
Done

2020-12-19 11:28 UTC, PHELAT approved these changes
LGTM.

2020-12-19 11:33 UTC, merged